image: golang:alpine

stages:
  - build
  - test
  - check_coverage

variables:
  EVENTDIR: event_service

build-job:
  stage: build
  script:
    - cd $EVENTDIR
    - go build -o bin/event cmd/main/main.go

test-job:
  stage: test
  script:
    - cd $EVENTDIR
    - go test ./... -coverprofile=coverage.out

check_coverage:
  stage: check_coverage
  script:
    - |
      COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
      echo "Coverage: $COVERAGE%"
      if [ "$COVERAGE" -lt 30 ]; then
        echo "Coverage is below 30%, failing the pipeline"
        exit 1
      fi
