services:
  gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${REST_SERVER_PORT}:${REST_SERVER_PORT}"
      - "${GRPC_SERVER_PORT}:${GRPC_SERVER_PORT}"
    networks:
      - netevent
  
  nginx:
    image: nginx
    container_name: nginx_container
    ports:
      - 80:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - gateway
    networks:
      - netevent

networks:
  netevent: