version: '3'
services:
  auth:
    build: ./auth
    container_name: auth_app
    # restart: always
    ports:
      - 6000:6000
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:latest
    container_name: redisdb
    restart: always
    ports:
      - ${PORT_REDIS}:6379
  postgres:
    image: postgres
    container_name: postgresdb
    restart: always
    ports:
      - "${PORT_POSTGRES}:5432"
    volumes:
      - ./auth/internal/data/postgres_data:/data
  nginx:
    image: nginx
    container_name: nginx_balanser
    volumes:
      - ./conf/:/etc/nginx/templates
    ports:
      - 8080:80