version: '3'
services:
  auth:
    build: ./auth
    container_name: auth_app
    # restart: always
    ports:
      - ${PORT_AUTH}:6000
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
  redis:
    image: redis:latest
    container_name: redisdb
    restart: always
    ports:
      - ${PORT_REDIS}:6379
    volumes:
      - ./data/redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
  postgres:
    image: postgres
    container_name: postgresdb
    restart: always
    ports:
      - "${PORT_POSTGRES}:5432"
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB:${POSTGRES_DATABASE}
      - POSTGRES_USER:${POSTGRES_USER}
      - POSTGRES_PASSWORD:${POSTGRES_PASWD}
  nginx:
    image: nginx
    container_name: nginx_balanser
    volumes:
      - ./conf/:/etc/nginx/templates
    ports:
      - 8080:80