version: '3'
services:
  auth:
    build: ./auth
    container_name: auth_app
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - ${PORT_AUTH}:${PORT_AUTH}
    networks:
      - authservice
  postgres:
    image: postgres
    container_name: postgresdb
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASWD}
    networks:
      - authservice
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    networks:
      - authservice

networks:
  authservice:
  # pgadmin4:
  #   image: elestio/pgadmin
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #       - 9000:80
  #   volumes:
  #     - ./servers.json:/pgadmin4/servers.json