// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type Notification struct {
	ID         int64
	UserName   string
	UserEmail  string
	EventName  string
	EventPlace string
	EventTime  time.Time
}
